version: '3.1'

services:

  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - '80:80'
      - '443:443'
    links:
     - nginx-production
    environment:
      #STAGE: 'production'
      #FORCE_RENEW: 'true'
      DOMAINS: >-
       $NGINX_SERVER_NAME -> http://nginx-production,
       $NGINX_WWW_SERVER_NAME -> http://nginx-production
      SERVER_NAMES_HASH_BUCKET_SIZE: 64
    volumes:
      - https-portal-data:/var/lib/https-portal
    networks:
     - proxy-tier

  nginx-production:
    image: nginx
    restart: always
    env_file: ./.env
    volumes:
     - ./nginx:/nginx
     - ./nextcloud:/var/www/html
     - php_socket:/var/run
    command: >
     /bin/sh -c "envsubst '$$NGINX_USER' < /nginx/nginx.conf.template > /etc/nginx/nginx.conf && 
     envsubst '$$PHP_VER$$NGINX_SERVER_NAME$$NGINX_WWW_SERVER_NAME$$NGINX_ROOT' < /nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && 
     nginx -g 'daemon off;'"
    links:
     - nextcloud
    networks:
     - proxy-tier

  nextcloud:
    build:
      context: php-fpm
      args:
       - NGINX_USER=$NGINX_USER
       - NGINX_GROUP=$NGINX_GROUP
       - NGINX_ROOT=$NGINX_ROOT
       - NGINX_SERVER_NAME=$NGINX_SERVER_NAME
       - PHP_VER=$PHP_VER
       - PHP_SESSION_DIR=$PHP_SESSION_DIR
       - NEXTCLOUD_VER=$NEXTCLOUD_VER
    env_file: ./.env
    restart: always
    volumes:
     - ./nextcloud:/var/www/html
     - php_socket:/var/run
    links:
     - mariadb
    networks:
     - proxy-tier

  mariadb:
    image: linuxserver/mariadb:latest
    restart: always
    expose:
     - "3306"
    env_file: ./.env
    volumes:
     - ./databases:/config/databases
    networks:
     - proxy-tier

networks:
  proxy-tier:

volumes:
  php_socket:
  https-portal-data: