version: '3.1'

services:

  nginx:
    image: nginx
    restart: always
    ports: 
     - 80:80
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/conf.d:/etc/nginx/conf.d
     - ./nginx/log:/var/log/nginx
     - ./nextcloud:/var/www/html
    depends_on:
     - nextcloud
    networks:
     - proxy-tier

  nextcloud:
    build: ./php-fpm
    restart: always
    expose:
     - 9000
    volumes:
     - ./nextcloud:/var/www/html
     - ./php-fpm/log:/var/log
    networks:
     - proxy-tier

networks:
    proxy-tier:
