version: '3.1'

services:

  certbot:
    build:
      context: certbot
    restart: always
    env_file: ./.env
    volumes:
     - ./nextcloud:/var/www/html
     - /var/run/docker.sock:/var/run/docker.sock
     - certs:/etc/letsencrypt
    depends_on:
     - nginx

  nginx:
    image: nginx
    restart: always
    env_file: ./.env
    ports: 
     - 80:80
     - 443:443
    volumes:
     - ./nginx:/nginx
     - ./nextcloud:/var/www/html
     - /var/run/docker.sock:/var/run/docker.sock
     - certs:/etc/letsencrypt
     - php_socket:/var/run
    command: /nginx/entrypoint.sh
    depends_on:
     - nextcloud
    networks:
     - proxy-tier

  nextcloud:
    build:
      context: php-fpm
      args:
       - NGINX_USER=$NGINX_USER
       - NGINX_GROUP=$NGINX_GROUP
       - NGINX_ROOT=$NGINX_ROOT
       - NGINX_SERVER_NAME=$NGINX_SERVER_NAME
       - PHP_VER=$PHP_VER
       - PHP_SESSION_DIR=$PHP_SESSION_DIR
       - NEXTCLOUD_VER=$NEXTCLOUD_VER
    env_file: ./.env
    restart: always
    volumes:
     - ./nextcloud:/var/www/html
     - php_socket:/var/run
    depends_on:
     - mariadb
    networks:
     - proxy-tier

  mariadb:
    image: linuxserver/mariadb:latest
    restart: always
    expose:
     - "3306"
    env_file: ./.env
    volumes:
     - ./databases:/config/databases
    networks:
     - proxy-tier

networks:
  proxy-tier:

volumes:
  certs:
  php_socket:
