version: '3.1'

services:

  nginx:
    image: nginx
    restart: always
    env_file: ./.env
    ports: 
     - 80:80
    volumes:
     - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
     - ./nginx/conf.d:/etc/nginx/conf.d
     - ./nginx/log:/var/log/nginx
     - ./nextcloud:/var/www/html
     - php_socket:/var/run
    command: /bin/sh -c "envsubst '$$NGINX_USER' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && envsubst '$$PHP_VER$$NGINX_SERVER_NAME$$NGINX_ROOT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
     - nextcloud
    networks:
     - proxy-tier

  nextcloud:
    build:
      context: php-fpm
      args:
       - NGINX_USER=$NGINX_USER
       - NGINX_GROUP=$NGINX_GROUP
       - NGINX_ROOT=$NGINX_ROOT
       - NGINX_SERVER_NAME=__NGINX_SERVER_NAME__
       - PHP_VER=$PHP_VER
       - PHP_SESSION_DIR=$PHP_SESSION_DIR
       - NEXTCLOUD_VER=$NEXTCLOUD_VER
    env_file: ./.env
    restart: always
    volumes:
     - ./nextcloud:/var/www/html
     - ./php-fpm/log:/var/log
     - php_socket:/var/run
    networks:
     - proxy-tier

networks:
  proxy-tier:

volumes:
  php_socket: