version: '3.1'

services:

  nginx:
    build:
      context: nginx
    restart: always
    env_file: ./.env
    ports:
     - "8080:80"
    volumes:
     - ./nginx:/nginx
     - /media/nextcloud-container-fpm/nextcloud:/var/www/html
     - /media/nextcloud-container-fpm/nextcloud_data:/var/www/nextcloud_data
     - nextcloud_var_run:/var/run
    tmpfs:
     - /var/cache/nginx/fastcgi_cache
     - /var/cache/nginx/fastcgi_temp
    command: >
     /bin/sh -c "envsubst '$$NGINX_USER' < /nginx/nginx.conf.template > /etc/nginx/nginx.conf && 
     envsubst '$$NGINX_SERVER_NAME$$NGINX_WWW_SERVER_NAME$$NGINX_ROOT' < /nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf &&
     echo 'SecRuleRemoveById 911100' >  /etc/modsecurity.d/owasp-crs/rules/zz-nextcloud.conf &&
     echo 'SecRuleRemoveById 920420' >> /etc/modsecurity.d/owasp-crs/rules/zz-nextcloud.conf &&
     echo 'SecRuleRemoveById 921110' >> /etc/modsecurity.d/owasp-crs/rules/zz-nextcloud.conf &&
     echo 'SecRuleRemoveById 949110' >> /etc/modsecurity.d/owasp-crs/rules/zz-nextcloud.conf &&
     nginx -g 'daemon off;'"
    links:
     - nextcloud

  nextcloud:
    build:
      context: php-fpm
      args:
       - NGINX_USER=$NGINX_USER
       - NGINX_GROUP=$NGINX_GROUP
       - NGINX_ROOT=$NGINX_ROOT
       - NGINX_SERVER_NAME=$NGINX_SERVER_NAME
       - PHP_SESSION_DIR=$PHP_SESSION_DIR
       - NEXTCLOUD_VER=$NEXTCLOUD_VER
    env_file: ./.env
    restart: always
    volumes:
     - /media/nextcloud-container-fpm/nextcloud:/var/www/html
     - /media/nextcloud-container-fpm/nextcloud_data:/var/www/nextcloud_data
     - nextcloud_var_run:/var/run
    links:
     - db

  db:
   image: jsurf/rpi-mariadb:latest
   restart: always
   env_file: ./.env
   volumes:
    - ./db/conf.d:/etc/mysql/conf.d
    - /media/nextcloud-container-fpm/mysql:/var/lib/mysql
    - nextcloud_var_run:/var/run

volumes:
  nextcloud_var_run:
